apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo
  namespace: default
spec:
  replicas: 3
  selector:
   matchLabels:
     app:web
  minReadySeconds: 10
  strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 0
   type: RollingUpdate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: app-site
        image: priya9272/python_project:2022-04-23--12-31
        readinessProbe:
          tcpSocket:
            port: 8070
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: app-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 8070
    targetPort: 8070
    nodePort: 30001
